CREATE TABLE "statuses" (
  "statusId" INT4 PRIMARY KEY,
  "tittle" VARCHAR(255) NOT NULL
);

CREATE TABLE "categories" (
  "categoryId" INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "tittle" VARCHAR(255) NOT NULL,
  "orderNumber" INT4,
  "statusId" INT4 NOT NULL,
  CONSTRAINT "Ref_categories_to_statuses"
    FOREIGN KEY ("statusId") REFERENCES "statuses"("statusId")
    ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE "tags" (
  "tagId" INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "tittle" VARCHAR(255) NOT NULL,
  "statusId" INT4 NOT NULL,
  CONSTRAINT "Ref_tags_to_statuses"
    FOREIGN KEY ("statusId") REFERENCES "statuses"("statusId")
    ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE "news" (
  "newsId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tittle" VARCHAR(255) NOT NULL,
  "shortText" VARCHAR(1024) NOT NULL,
  "fullText" TEXT,
  "publishedAt" TIMESTAMPTZ NOT NULL,
  "authorName" VARCHAR(255) NOT NULL,
  "categoryId" INT4 NOT NULL,
  "tagIds" INT4[],
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "statusId" INT4 NOT NULL,
  CONSTRAINT "Ref_news_to_statuses"
    FOREIGN KEY ("statusId") REFERENCES "statuses"("statusId")
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "Ref_news_to_categories"
    FOREIGN KEY ("categoryId") REFERENCES "categories"("categoryId")
    ON DELETE RESTRICT ON UPDATE RESTRICT
);
